export enum EntityType {
  DETECTION = 'DETECTION',
  CVX = 'CVX',
  ADF = 'ADF',
  CONFIGURATION = 'CONFIGURATION',
  TEMPLATE = 'TEMPLATE',
  SECTION = 'SECTION',
  JOB = 'JOB', // ANALYSIS JOB
  MERGE_JOB = 'MERGE_JOB',
  FACILITY = 'FACILITY',
  USER = 'USER',
  REPORT = 'REPORT',
  QUERY = 'QUERY',
}
